#!/usr/bin/env bash
set -euo pipefail

SPEC_FILE="${1:-docs/apis/xendit-openapi-from-postman.json}"
OUT_FILE="${2:-internal/cli/xendit_openapi_aliases_generated.go}"
VAR_NAME="${3:-generatedXenditAPIOperationAliases}"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
if [[ "$SPEC_FILE" = /* ]]; then
	SPEC_PATH="$SPEC_FILE"
else
	SPEC_PATH="$ROOT_DIR/$SPEC_FILE"
fi

if [[ "$OUT_FILE" = /* ]]; then
	OUT_PATH="$OUT_FILE"
else
	OUT_PATH="$ROOT_DIR/$OUT_FILE"
fi

mkdir -p "$(dirname "$OUT_PATH")"

node - "$SPEC_PATH" "$OUT_PATH" "$VAR_NAME" <<'NODE'
const fs = require('fs');

const specPath = process.argv[2];
const outPath = process.argv[3];
const varName = process.argv[4] || 'generatedOpenAPIOperationAliases';
if (!specPath || !outPath) {
	throw new Error('usage: generate-xendit-openapi-aliases.sh <spec-path> <out-go-file> [var-name]');
}

const rawSpec = fs.readFileSync(specPath, 'utf8');
const spec = JSON.parse(rawSpec);
const HTTP_METHODS = new Set(['get', 'post', 'put', 'patch', 'delete', 'head', 'options', 'connect', 'trace']);

function sanitizeAlias(value) {
	return value
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/-+/g, '-')
		.replace(/^-|-$/g, '');
}

function withoutVersions(segments) {
	return segments.filter((segment) => {
		if (!segment) {
			return false;
		}
		const isPlaceholder = segment.startsWith('{') && segment.endsWith('}');
		if (isPlaceholder) {
			return false;
		}
		if (/^v\d+$/i.test(segment)) {
			return false;
		}
		if (/^v\d+(?:\.\d+)+$/i.test(segment)) {
			return false;
		}
		if (/^\d+$/.test(segment)) {
			return false;
		}
		return true;
	});
}

function maybeSingularize(value) {
	if (!value || value.length <= 3 || !value.endsWith('s')) {
		return '';
	}
	if (value.endsWith('ss') || value.endsWith('us') || value === 'status') {
		return '';
	}
	return value.slice(0, -1);
}

function buildAliases(path, method) {
	const normalized = String(path || '').split('?')[0].trim();
	if (!normalized) {
		return [];
	}

	const methodLower = String(method || '').toLowerCase();
	const segments = normalized
		.split('/')
		.map((segment) => segment.trim())
		.filter((segment) => segment.length > 0);

	const aliases = new Set();
	const allVariants = [
		withoutVersions(segments),
	];

	for (const variant of allVariants) {
		const compact = [...new Set(variant)];
		if (compact.length === 0) {
			continue;
		}

		const baseAlias = sanitizeAlias(compact.join('-'));
		if (baseAlias) {
			aliases.add(baseAlias);
			const baseSingular = maybeSingularize(baseAlias);
			if (baseSingular) {
				aliases.add(baseSingular);
			}
		}

		const lastAlias = sanitizeAlias(compact[compact.length - 1]);
		if (lastAlias) {
			aliases.add(lastAlias);
			const singularLast = maybeSingularize(lastAlias);
			if (singularLast) {
				aliases.add(singularLast);
			}

			if (methodLower) {
				aliases.add(`${methodLower}-${lastAlias}`);
				if (singularLast) {
					aliases.add(`${methodLower}-${singularLast}`);
				}
			}
		}
	}

	if (methodLower) {
		for (const alias of Array.from(aliases)) {
			if (alias.startsWith(`${methodLower}-`)) {
				continue;
			}
			aliases.add(`${methodLower}-${alias}`);
		}
	}

	return [...new Set(Array.from(aliases))];
}

const generated = new Map();
	for (const [rawPath, methods] of Object.entries(spec.paths || {})) {
	if (typeof methods !== 'object' || methods === null) {
		continue;
	}

	for (const [rawMethod, operation] of Object.entries(methods)) {
		const methodLower = String(rawMethod || '').toLowerCase();
		if (!HTTP_METHODS.has(methodLower)) {
			continue;
		}
		if (typeof operation !== 'object' || operation === null) {
			continue;
		}

		const method = methodLower.toUpperCase();
		if (!method) {
			continue;
		}

		for (const alias of buildAliases(rawPath, method)) {
			if (!alias || generated.has(alias)) {
				continue;
			}
			generated.set(alias, { method, path: rawPath });
		}
	}
}

function formatGoString(value) {
	return JSON.stringify(value);
}

const entries = [...generated.entries()].sort(([a], [b]) => a.localeCompare(b));
let output = '// Code generated by scripts/generate-xendit-openapi-aliases.sh. Do NOT EDIT.\n';
output += '\n';
output += 'package cli\n\n';
output += `var ${varName} = map[string]pathTemplateOperation{\n`;

for (const [alias, value] of entries) {
	output += `\t${formatGoString(alias)}: {method: ${formatGoString(value.method)}, path: ${formatGoString(value.path)},},\n`;
}

output += '}\n';
fs.writeFileSync(outPath, output);
console.log(`wrote ${outPath}`);
NODE
